language: ruby

rvm:
  - 1.9.3

before_install:
  - git submodule update --init --recursive
  - sudo ./bin/init

script:
  - sudo env PATH=$PATH gem install bundler
  - sudo env PATH=$PATH bundle install
  - sudo env PATH=$PATH bundle exec rspec spec
