---
jobs:
  - name: legna
    template: angel
  - name: yellows
    template: yellows
  - name: fail_job
    template: fail_job

properties:
  miku:
    san:
      maji: tenshi
  hide:
    value: true
